### ISSUE TITLE
Gray Canvas on Startup, Cant even draw.

### ISSUE THREAD

**Issue by TayLife12** [opentoonz/opentoonz#1775]
Heya!

I just got this for the first time and watched a tutorial on how to set up the scene. I did all that successfully, but unlike videos where the canvas is white, mine is gray. I can see in the little tab to left what I draw on the gray canvas, but not on the canvas itself.

http://prntscr.com/i6x4qn

**Comment by RodneyBaker** [comment]
Thanks Tay,
You have encounntered a known problem that has been fixed but you'll need to install the nightly build, OTX or Morevna releases to get it as that fix hasn't been incorporated yet into the official release.

I looked for the original report but didn't locate it.

Recommend close as duplicate.

**Comment by TayLife12** [comment]
Thanks for responding,
Where can I find the the list for the Builds?

**Comment by RodneyBaker** [comment]
The nightlies can be found here:

https://github.com/opentoonz/opentoonz_nightlies/releases

OTX (OpenToonz Experimental) can be had here:

https://gumroad.com/l/TZmmM

(Jeremy... the author says it's fine to enter $0 for the download)

The Morevna Edition can be had here:

https://morevnaproject.org/opentoonz/

(There is an anonymous download link for those that don't want to financially contribute.... and if a 32bit release is desire the folks at Morevna are the ones behind that too)

**Comment by TayLife12** [comment]
Thanks for helping me so far, Im having some trouble installing. I got the .exe from nightlies and ran it, but still same up with gray. Im not sure if I am doing something wrong or its just still broken.

**Comment by RodneyBaker** [comment]
I haven't entirely followed the other topics because I haven't been having the problem myself so perhaps I should have suggested those in another order of preference.

It may be that the nightlies which are associated with the official release have not yet incorporated the specific fix you require.

The Morevna Edition has been suggested to resolve the problem and has worked for others.

If for some reason Morevna doesn't work we may need to wait until someone more familiar with the problem steers us right.

It may be that the topic I am thinking of is in the OpenToonz forum... gah... found the reason I couldn't find it... I was spelling gray the wrong way.  It's spelled 'grey' in the forum.

Try this: https://github.com/opentoonz/opentoonz/issues/1674

Which was recently referenced by this:

**Comment by manongjohn** [comment]
You are better off installing OTX or the Morevna edition than use the nightly.

I find it ridulously absurd they haven't fix this yet.

**Comment by TayLife12** [comment]
Alright the Morevna edition worked! Thanks guys!

**Comment by RodneyBaker** [comment]
I will guess that rather than fix the immediate problem they may be trying to fix the whole thing while still moving forward.  Thats more of a hope than a guess.

Glad to hear that worked Tay!  Now get to animating!  :)
