### ISSUE TITLE
Fill tool crashes OT Morevna

### ISSUE THREAD

**Issue by Ncln10** [opentoonz/opentoonz#1829]
Selecting fill tool crashes the program. (no effect in raster, crash in vector)
Windows 10 64 bits - OT Morevna 1.2.0.2 -
A few days ago I installed OT 1.2.0 : worked and later crashed the program.

Other issue : brush tool does not work.

**Comment by Ncln10** [comment]
I have uninstalled OT Morevna 1.2.0.2 and all the files, installed OT 1.2.0 built dec 11 2017.
And now, fill tool works !
I'm discovering and beginning to test this, with tablet Wacom Intuos Pro too : no problem for the moment.
FX effects work but I'm asking : where can I find detailed explications about them ?

**Comment by Ncln10** [comment]
I have uninstalled OT Morevna 1.2.0.2 and all the files, installed OT 1.2.0 built dec 11 2017.
And now, fill tool works !
I'm discovering and beginning to test this, with tablet Wacom Intuos Pro too : no problem for the moment.
FX effects work but I'm asking : where can I find detailed explanations about them ?

**Comment by RodneyBaker** [comment]
Glad to see you've got it working.

I've started a topic in the OpenToonz forum to try to collect some information and resources related to FX.

It won't be of much help at present but that topic can be found here:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!category-topic/opentoonz_en/general-discussion/YLIOh1pTXlw

**Comment by RodneyBaker** [comment]
Recommend closing this issue.

**Comment by Ncln10** [comment]
Thank you very much RodneyBaker for these very useful informations.

**Comment by Ncln10** [comment]
**New crash again !** Fill tool does not work, selecting it crashes the program.
Everything was ok for 2 days and suddenly without any reason this tool does not work.
(W10 64 bits - OT 1.2.0 built dec 11 2017)
It was the same issue with OT Morevna 1.2.0.2.
What can I do ?

**Comment by shun-iwasawa** [comment]
It's probably the same crash as #1737 .
The problem was fixed with #1738 and is already included in the latest nightly build.
Please try installing the nightly build available [here](https://github.com/opentoonz/opentoonz/releases).

**Comment by morevnaproject** [comment]
@Ncln10 As a temporary workaround: avoid setting Fill Tool to "Line". Or stick with official version of OpenToonz.

For Morevna Edition the fix will be shipped in upcoming versions.

**Comment by Ncln10** [comment]
I use now the latest nightly build : fill tool is OK.
Thank you.

**Comment by aurorasystemsus** [comment]
I have the latest build as of March 2021 and it crashes out my program too.. not fixed...
