### ISSUE TITLE
Open Toonz crashing after switching navigation tools 

### ISSUE THREAD

**Issue by NestorAntonio** [opentoonz/opentoonz#1913]
Hello, a long time ago I had an Issue with Open Toonz, that it will crash after drawing on a raster level. 
Recently reading the issue  #860, and after doing some tests I realized that it wasn't a graphic problem, it was that when I'm using the hand tool or the rotate tool, holding the button,  If I release it and keep dragging with the stylus the software will crash.  Looking at the comments in #860  I'm seeing that there were some solutions to be implemented in future releases of Open Toonz. Do you know how I could solve it? I'm using the OPT modified version by # @turtletooth.

Thanks in advance, and thanks for all the hard work on OPT.

**Comment by jpturcotte** [comment]
The changes mentioned in #860 have already been included in version 1.2 & up. It might still be related, though.

**Comment by NestorAntonio** [comment]
Yes, I thought it was something related. I'm using OPT 1.2, though today I made several tests with the zoom tool, and the eraser tool and it happens the same. It doesn't seems to occur if I use the brush tool. The other thing that I noted is that the problem seems to happen only on a raster level.

**Comment by jpturcotte** [comment]
Thanks for the additional info!

**Comment by artisteacher** [comment]
Does this still happen with the most recent nightly build? The touchpad touch fix included a fix for certain stylus button behaviors.

**Comment by NestorAntonio** [comment]
Hello Artisteacher, I did a test with the latest nightly build, though still happens the same. Is there a work around I could use? 

Thanks in advance.

**Comment by artisteacher** [comment]
Have you tried turning on the touch controls?

**Comment by NestorAntonio** [comment]
Hello, I just tried turning on the touch controls but the problem still persist. At the time of drawing with the brush tool on a raster level, and then using a navigation tool, it could be the hand, the zoom or the rotate tool, holding the button.. If I release it while the tip of the pencil (left click) it's still touching the screen, OPT crashes.

**Comment by artisteacher** [comment]
Just to clarify, did you try using the touch behaviors to navigate without the stylus as a way to avoid the crash? 1 finger drag = panning, 2 finger twist to rotate, pinch to zoom in/out, double tap to reset view, 3 finger swipe to undo/redo.

**Comment by NestorAntonio** [comment]
Yes I did, though it's a bit uncomfortable due to the the way my cintiq and my laptop are set up. Perhaps more practice will do.

**Comment by manongjohn** [comment]
This was duplicated in #2361 but on a Windows machine. It's been fixed with PR #2362 and should have also corrected on Macs.

**Comment by RodneyBaker** [comment]
@NestorAntonio Please let us know if this problem has been addressed via the fix @manongjohn has implemented.  Thanks!

Note:  There are still some other navigation/switching anomalies being addressed so please report any  encountered.

**Comment by RodneyBaker** [comment]
@NestorAntonio can you open a separate issue for that one?
It may be in the pipeline to be fixed already but the extra focus on specifics can help.
Thanks!

Glad to see the fix worked!

**Comment by NestorAntonio** [comment]
> 
> 
> @NestorAntonio can you open a separate issue for that one?
> It may be in the pipeline to be fixed already but the extra focus on specifics can help.
> Thanks!
> 
> Glad to see the fix worked!

Hello Rodney, sorry I know this Issue was closed, but I just noticed this problem still happens on Full Screen mode, however in normal mode it's now solved.
