### ISSUE TITLE
link all selected elements

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#3794]
**Is your feature request related to a problem? Please describe**
when dealing with a ton of layers in FX or even in schematic, you would have to manually connect every element to the destinated effect or composite

**Describe the solution you'd like**
selecting all desired elements > select target effect "over node" pressing ctrl or alt or shift
selecting all desired elements > right click target effect/over node -connect here- option
![OpenToonz_HBy9IfvM70](https://user-images.githubusercontent.com/36406840/111883234-c058a000-8998-11eb-9e54-5ed17dfcdf6b.png)

**Comment by shun-iwasawa** [comment]
FYI as a tricky workaround you can connect multiple nodes to OverFx by the following steps:

1. Collapse the multiple columns to sub-xsheet.
    <img src="https://user-images.githubusercontent.com/17974955/111887464-98a91c80-8a18-11eb-9411-56c86134375a.png" width=200> <img src="https://user-images.githubusercontent.com/17974955/111887495-be362600-8a18-11eb-9c50-1784f711f1a9.png" width=200>
2. Insert some fx between the sub-xsheet node and the Xsheet node.
    ![image](https://user-images.githubusercontent.com/17974955/111887542-005f6780-8a19-11eb-9c3d-36ab3c8970b1.png)
3. Explode the sub-xsheet
    ![image](https://user-images.githubusercontent.com/17974955/111887562-1cfb9f80-8a19-11eb-8ea3-bc9605eb6578.png)
4. Ungroup the node. All nodes are now connected to OverFx.
    <img src="https://user-images.githubusercontent.com/17974955/111887581-4b797a80-8a19-11eb-8f5f-822e2c4b53f4.png" width=300>

Please note that the trick is only for connecting the nodes to OverFx.

**Comment by age3rcm** [comment]
the bad part is that it messes up with your keyframes, losing them in the process of making everything into a sub-xsheet

**Comment by shun-iwasawa** [comment]
Can you please clarify which keyframes are lost when collapsing? 
I rarely use features related to cut-out animation so I may miss something, but at least the transformation keyframes of the columns are brought into the sub-xsheet.

**Comment by age3rcm** [comment]
i have done the operation of collapsing then exploding and ungrouping all the layers after turning the computer on and off (i had left my house) aaaaaand the keyframes has been preserved this time

now lets try something else:
i will do the same operation, but i will link a "overFX" after the sub-xsheet
i clicked on "explode" and "ungroup"every element has its own "overFX" linked to next "overFX" daisy-chain style
and the keyframed z depth lost its function
![OpenToonz_SiB6BPbZET](https://user-images.githubusercontent.com/36406840/111890586-763be280-89c9-11eb-9384-4ae26f69fd9e.png)

**Comment by age3rcm** [comment]
![cjbronyten3 0001](https://user-images.githubusercontent.com/36406840/111890604-9f5c7300-89c9-11eb-807c-ada0f8d7d70c.png)
![cjbronyten3912 0001](https://user-images.githubusercontent.com/36406840/111890606-a1263680-89c9-11eb-8f01-8eab400c4967.png)
for refference, there is one image with background where the zspace keyframes work and the image is right
the other without background, the z space without doing its function with the fx schematic like the previous post

**Comment by shun-iwasawa** [comment]
> i will do the same operation, but i will link a "overFX" after the sub-xsheet i clicked on "explode" and "ungroup"every element has its own "overFX" linked to next "overFX" daisy-chain style

Hmm I couldn't reproduce the chaining-overfx behavior. It seemed to explode properly at my end:
<img src="https://user-images.githubusercontent.com/17974955/111895859-d75ec700-8a58-11eb-9c1f-4daad62587d3.png" width=300>


> and the keyframed z depth lost its function

Regarding the stacking order of the columns, please note that `Z` and `SO` values are considered ONLY for the columns connected to the Xsheet node. If the columns are connected to another composite fx nodes like `OverFx` , they will be stacked as the fx specifies.

**Comment by age3rcm** [comment]
> Hmm I couldn't reproduce the chaining-overfx behavior. It seemed to explode properly at my end:

try "ungroup" the group there?

**Comment by shun-iwasawa** [comment]
I think I get the point.
Are you using V1.4 stable version? If yes, the similar problem had been reported in #3348 and fixed in #3349 .

**Comment by age3rcm** [comment]
yes, it was 1.4

**Comment by RodneyBaker** [comment]
I believe this method to link selected nodes works.
@age3rcm If you can clarify what still remains that will be appreciated.

**Comment by age3rcm** [comment]
well, i use 1.7.1 and i still not see a solution for this issue.
in toonboom, its simple as that, select the columns on fx schematic and click pressing ctrl on the over node it gets all connected
it is not in conflict with any workflow and it helps the user
