### ISSUE TITLE
Created folders doesn't show in the "Save as" window

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#4704]
### Description

When I try to create new folders in the "Save all" window, Opentoonz doesn't show them.

### Steps to Reproduce

1. Create a new scene.
2. Go to file and "Save all" (Ctrl+S)
3. Create a project folder and rename it from that window.
4. Try to create several folders into it.

### Expected Behavior

The expected is to be able to see the folders created.

P.D: I have to say that sometimes I can see the created folders, but it looks something randomized.

**Edit:** 

I have the $cenepath option On

![1](https://user-images.githubusercontent.com/74098734/211800510-e46759ca-de11-4bfd-946e-38e32bfb78ce.jpg)
![2](https://user-images.githubusercontent.com/74098734/211800519-91723e4a-8967-46b8-abf9-955d7416d846.jpg)

### Screenshots, Video & Crash Logs

![a0a0fea29815785ca8167be29306de0c](https://user-images.githubusercontent.com/74098734/211799000-24a82f7a-4aa4-4c95-83e4-b4b3667bebd8.gif)

### OpenToonz Version

1.6

### OpenToonz Version Information

Last build

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
I haven't scrubbed the reports for this but this problem sounds familiar.
I believe it might have been addressed in Tahoma2D.

**Comment by F-Burning** [comment]
Yes, I don't remember exactly the problem, but there was a similar issue to this one, and in theory it was solved.

**Comment by RodneyBaker** [comment]
This is just a note to suggest there are a number of locations in Opentoonz where directory listings do not update.
This can take on various forms but in general the directory listings simply do not refresh.
Taking inventory of all the specific locations where this occurs will likely lead to a resolution resolving most if not all of those shortfalls.

**Comment by RodneyBaker** [comment]
Here's a question for you @F-Burning (which I am currently investigating)...

In #1060 an Preferences option was created to keep Opentoonz for constantly watching and updating files and directories... presumably as that takes time and can slow down various processes.

Turning this option off in `Preferences > General` adds a '`Refresh`' button to the menu bar and to the Right Click panel.
The question then...

### If we turn the option to Watch File System off and use the refresh button/menu, does that make the folder(s) appear that were not appearing before?

If it does then perhaps the refresh option could remain on regardless of whether the Preference to watch the file system is on or off.  Then the user would be able to update the listing manually in cases where the listing fails to update automatically.

**Comment by F-Burning** [comment]
@RodneyBaker 

I just did the test using the manually refresh option and the new folders still don't show up.

**Comment by RodneyBaker** [comment]
Please update to the latest nightly release:  https://github.com/opentoonz/opentoonz/releases

If you still experience problems after updating let us know.
