### ISSUE TITLE
feature - Inbetween (tween) onion skin mode!

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#565]
This is a request for a new onion skin mode that gets enabled when multiple frames in the level strip are selected and the 'inbetween' buttons appear.
The mode allows you to get a good idea of the order in which lines are drawn in the refference frame and it also shows you the direction.

The easiest way to illustrate it is by looking at Cacani  - 
https://www.youtube.com/watch?v=NQEgL8tZg-0

The onion skin displays only the first previous/next reference keyframe.
It also highlights the one stroke from the previous frame (depending on how many strokes you have made so far on the active one)  that corresponds to the one that you are about to make.

We can get this feature in opentoonz if somebody knows how to implement it. it will be incredibly useful to have!

![onionhighlight-inbetween](https://cloud.githubusercontent.com/assets/6495061/16528892/7e20aa3c-3fb7-11e6-8c79-477f0797b9d4.PNG)

In order to enable the inbetween onion skin mode, simply select multiple frames in the level strip - this also brings the 'inbetween' buttons.

Depending on where your active frame is and last selected frame is - the onion skin looks back or forth.
Even if there are lines in the inbetween frames - the onion skin ignores them. It only cares about the inbetween refference frame (0001 in this case).

The onion skin inbetween reference frame displays in a different color than the normal onion skin (purple?) -  and also draws a direction hint on top of one of the lines (>>>>>>) - that way it highlights the correct line in the order you are drawing and also its direction.

@walkerka Can you really implement this? This would be the second time you radically improve the software with a single blow. ;) 
The OT community will love you even more.
A lot of people have been crying out for this feature on other animation software. 
It's a simple, but very powerful feature that makes the process of automatic tweening much easier and organic.

**Comment by blurymind** [comment]
This is like the holy grail for cleanup artists and inbetweeners. I am not gonna lie. :D 
It is so much better than simply copy and pasting the entire drawing to deform it.

**Comment by blurymind** [comment]
And here it is in action - in tweenmaker - Note how the onion skin outlines the line order you are at and also the direction:
![sequentianonionskin](https://cloud.githubusercontent.com/assets/6495061/16536140/0e107b76-3fe6-11e6-81f2-7377a30ad038.gif)

because a single picture speaks volumes.
This is a really nice way to work btw.

**Comment by walkerka** [comment]
@blurymind I don't know these softwares before. It looks we're sharing similar ideas. Harmony also have smilar function called "Morph". It doesn't show the ordering though.

I just implemented basic stroke to stroke inbetween generation in my editor now. It's almost same as TweenMaker. There're still many issues:

1. Motion path
The motion path of a stroke point is always a straight line now. It's incorrect in most cases. Most drawing follows a curve instead of a straight line. Different drawing parts usually follow different paths. There's no good way to make them move consistently right now.

2. Timing control
The inbetween is evenly divided right now. It should support manually indicated timing. Users should be able to decide the position of a stroke end point accurately. (So they can sync with other drawings)

3. Breakdown
Even the simplest animation changes in stroke count and order. Need find a way to add breakdowns between two key frames.

4. Contact points
As the stroke moves, there's no guarantee that connected points still stick to the stroke. Need some data structures to keep these infos.

I need find solutions for these issues before implementation.

**Comment by walkerka** [comment]
Here's a demo of current work progress in my editor. 
[https://www.youtube.com/watch?v=ApxIvBjtlPw&feature=youtu.be](https://www.youtube.com/watch?v=ApxIvBjtlPw&feature=youtu.be)

As I mentioned, the inbetween only moves along straigth line. I have to draw several breakdowns to make it move smoothly.

**Comment by blurymind** [comment]
@walkerka This looks very close to the idea of this feature request.
It is missing two key points however:
- The onion skin does not display the line direction
- The onion skin should only show the previous reference frame - in the video it shows 2 previous frames - like a traditional onion skin - which is not that bad but it is unnecessary 

I think that your system while still not perfect- is already pretty good. You have a good and ambitious plan to create something really special. 
The system is made out of elements - some of which can be merged to opentoonz with some work already. 

This proposal is only for the onion skin feature - which you already have almost implemented.
Since your plan is made of much more than that - I propose to take a step by step approach - that way it will be easier to get these improvements merged to open toonz.

Would it be possible to get the tweening onion skin feature ported to opentoonz and get it to show line direction? Then continue to develop the other improvements. That would benefit current users immensely and make it easier to get the merge approved.

All the other elements we can break into different issues to be tackled one by one.

**Comment by blurymind** [comment]
Another point I should have mentioned is that this onion skin mode should actually work on the **x-sheet** - otherwise it would be impossible to see the rough pass keyframe drawings - which are presumably on another level!

**Comment by walkerka** [comment]
My inbetween generator detects the direction of stroke pair automatically. It works in most cases. So there's no need to care about the direction. You know some strokes are very hard to draw from the reverse direction. Sometimes it fails so I plan to add a command to manually set the direction of some strokes.
The onion skin in my editor is configurable (count/enable/position/relative/transform/color/opacity). It can be turned off separately anytime.

The onion behavior (including the level strip) of OT is a little hard to understand. I need to learn how to use it first. Then see if it's easy to add stroke highlight feature. Currently I'm busy on my editor development so it may be delayed.

**Comment by blurymind** [comment]
@walkerka Ah I see. I will create a new issue on the inbetweening while being able to see other levels later. It is a bit hard to explain - so I need to illustrate it with an example. :)

On this feature - I guess the request is not an entirely new tweening feature - which is what you are doing. But for a single onion skin feature that would compliment the current one in a great way. After that we can replace the current tweening system gradually.

**Comment by blurymind** [comment]
@walkerka On the point about needing to create breakdowns - in Cacani they solve this by being able to give the inbetween an Arch curve to work with

https://www.youtube.com/watch?v=0OJxbao5XeM

**Comment by blurymind** [comment]
@walkerka  In order to solve the design problem with the multilevel inking + inbetweening - we need to first get the onion skin feature in this issue thread. If you implement it before solving all the other problems in your editor - it will get the ball rolling for me to design a proposal of how to solve the next bits missing.
Since these features are interconnected - they need to be implemented in certain order

**Comment by walkerka** [comment]
@blurymind The inbetween function of Cacani looks amazing. I'll take a look at it more carefully. Does any company use it in real production?

I'm not familiar with OT's inking system. The best one I've seen is TVP's lazybrush. I developed a faked one based on color strokes. Also improves the multiple shade levels coloring by a composition graph (performs some tricks on the palette). It's faster than the normal way but have some performance issues.

**Comment by blurymind** [comment]
@walkerka  
i thought about this and experimented. it looks like multilevel inbetweening would be possible to do - but the inbetween onion skin mode would have to be triggered in a different way than the one I originally proposed- It will need to be triggered for the x-sheet rather than the level strip. Only that way we will be able to still see the blue pencil while we do it!

Here is how it could work:
![sequentialonionskin-xsheet](https://cloud.githubusercontent.com/assets/6495061/16542762/36548f5a-40ae-11e6-9519-476bc73a12c3.png)

We have two levels - the rough pass (blue pencil) and the cleanup pass (black pen).
We need to do the inbetweening on out cleanup pass level.

While we do it, the onion skin in the x-sheet could have an optional (enable in preferences)  mode that shows you hinting direction points on top of one of the lines in the previous frame.Which one depends on how many lines you have drawn so far on the current frame. 
This way you would know exactly where to make the next black stroke - and also be able to see the blue pencil reference level at the same time!

**Comment by blurymind** [comment]
@walkerka here is the  showcase page of cacani: https://cacani.sg/#!/showcase
I think it has been also used on afro samurai - some of their learning videos had a few shots out of it.

**Comment by walkerka** [comment]
I see. OT only shows working level in onion skins. In level strip mode doesn't show other level's drawing at all. So it's impossible to reference a rough sketch in that mode.
Animated highlights is more user friendly but it may cause lag in user operations. Because it keeps rendering which consumes much more CPU/GPU resources.

**Comment by blurymind** [comment]
@walkerka OT has two drawing modes - each with it's own onion skin - for x-sheet and for level strip.
If this feature is to be added - it will need to go to the x-sheet onion skin, because selecting frames in the level strip switches opentoonz to the level strip mode and hides all the other levels.
We can of course still do cleanup while being able to see the other levels - when drawing on cells in the x-sheet. Drawing on an empty cell creates a new level strip frame.

**Comment by konero** [comment]
I'm sure people are using it in production, though when I tried it nobody liked it, the harshest criticism was somebody saying "it doesn't feel like I'm animating at all" and people seem unhappy with the perpetual license needing to phone home, since its a new company it seems a flaky investment to some people, so building a studio on it seems too risky.

This is a bit tl;dr, but I'm guessing this FR is about stroke order and direction? Then I do like how CACANi does it.

Arrows indicate direction, you can flip the stroke direction of a single stroke if you get it wrong later too and redo the inbetweens.

I don't like the animated highlight version for the same reasons @walkerka described.

**Comment by blurymind** [comment]
@konero this FR is for the onion skin hinting. So yes- show the line in the correct order and its direction. How that direction is displayed is up to whoever implements it. :). I personally dont think that it would lag if the gpu is used, but yes performance is priority obviously. 

As for cacani itself - it does one thing and does it well-  generating inbetweens. that is the cleanup stage, not the animation stage. It uses a similar approach to open toonz, but is obviously a different beast.
I am not asking to turn OT into cacani - just to get the onion skin feature. I also presented another example software that has it. What do you think of the way tweenmaker does it? Do you like it more?

**Comment by blurymind** [comment]
One thing to add to this feature request- only hint lines that use the same style as the one you currently have - if possible. Also hint invincible lines

**Comment by blurymind** [comment]
@walkerka would it be possible to port your solution over to OT and make it an optional Onion Skinning mode?

Even if it's not complete in your eyes, it would add a lot of value to the current tweening workflow - as it displays the correct order of line drawing. It doesnt display the line direction,but that can be added further down the line.

Getting it in would get the ball rolling at least :)

For line drawing OT devs must decide between:
- Refactoring some of the tweening code to support automatic tweening that doesnt require correct line direction

or

- Add support for line direction display in the tween onion skin mode

The second would likely be easier to merge, as it doesn't require rewriting already functional/stable parts of the software

**Comment by jotokutora** [comment]
Nice work. @ blurymind, I will have to clarify that CACANi did not used "Tweenmaker" as reference  for the stroke matching. Cacani started development back in 2001 but was not commercially available until recently. That said best on this project!

**Comment by jotokutora** [comment]
Regarding If CACANi is currently used in professional studios? Yes, mainly asian countries including, China, Korea and Japan.

**Comment by blurymind** [comment]
I believe strogly that without tween preview in onion skin, the tweening workflow in opentoonz is not complete and not competitive with cacani

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by blurymind** [comment]
This can be considered as solved now, since the awesome @turtletooth  implemented it :D 
Thank you thank you thank you!
