### ISSUE TITLE
Crash rendering rigged animation (Plastic Tool)

### ISSUE THREAD

**Issue by chrononath** [opentoonz/opentoonz#5780]
### Description

Every time iI ry to render or simply preview my animation where i used the plastic tool, the program crashes.
I tried:
- different file formats (mp4, png, gif, tif, tga),
- using the least possible meshes, 
- using a smaller resolution (around 700x900 px)
- restarting the project from scratch in a new scene

none of these worked.
i tried the plastic tool once before with just two levels and it had no issue exporting it because the animation was really simple, but this project has around 18 levels and 40 frames.

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
Without knowing more about your specific project it can be hard to diagnose the problem and suggest specific remedies.  There are some general things to watch out for when using Plastic to increase the chances of success.  Examples include:

- Save All at each major change of the scene
- Clear the cache via File > Clear Cache Folder
- Turn off Autosave so it won't attempt to interupt a process 
- Update Opentoonz (as some fixes to problems likely have been addressed in the nightly releases)
- Consider holding off on other memory intensive processes while working with Plastic
- Simplify the scene by rendering or merging columns/parts of objects/characters and apply Plastic to that composite
- Consider using Task Rendering rather than standard render through Output Settings

It sounds a bit like you are running out of memory/resources which is not your fault but rather an issue with complex scenes with FX and/or Plastic.  To test output you might stick with a larger resolution but while testing use a Shrink value of 4 or 5 just to drop the resolution during that testing.  Once a render is successful then its trivial to change that Shrink value to 1 or 2 (full or half size).  The same can be done for previews via Preview Settings, just make sure the option to use that same setting for the canvas is toggle on.

Let's see, what else did you mention:

```different file formats (mp4, png, gif, tif, tga),
using the least possible meshes,
using a smaller resolution (around 700x900 px)
restarting the project from scratch in a new scene```

Stick with PNG or TIF image sequence output to help free up memory faster.  Recompile that sequence into video (MP4) later.

The least possible amount of meshes is 1 so... consider using one mesh but be innovative when placing your images on canvas and in rigging so those objects can all be controlled inside that one rig/mesh.  (certainly not a requirement but... 1 is the least amount of meshes we can use).  We can also use multiple skeletons in the same mesh setup... and multiple meshes in the same column... lots of variables here and different workflows.

I mentioned using Shrink value when rendering tests.  Highly recommended and fast to change.  Also keeps us from unnecessarily changing the settings we want for our final output.

If you have keyframes on your columns you might be getting a conflict so consider collapsing your columns down into a sub-xsheet (or two).  For instance, you might have one sub-xsheet for non rigged objects and another for the rigged object(s).  Collapsing into a sub-xsheet is a near equivalent to 'baking' an action in other programs although unlike baking it is a process we can back out of easily.  It does help lock down keyframes and interpolations which can get pretty complex quickly when animating.

Restarting the project via a new project; this I can't say much about because I don't know the extent of what your project consists of.  Its a good way to move past problems in a troublesome scene so its good to know you've tried that.

**Comment by RodneyBaker** [comment]
Please update to the latest nightly release:  https://github.com/opentoonz/opentoonz/releases

If you still experience problems after updating let us know.

**Comment by chrononath** [comment]
Hi, i updated to the latest nightly build, but the problem persists.

- I often click Save All, so I do not think that is the issue;
- I tried clearing the cache;
- the autosave option was already off;
- i tried having only the opentoonz software open while working with Plastic Tool.

The last two methods are not clear to me:
- I'm not sure how to merge columns and apply Plastic to that
- I can't find Task Rendering in Output Settings

**Comment by RodneyBaker** [comment]
Task Rendering
Task Rendering is actually it's own room/tab over to the upper right of the application.
We can add scenes to Task Rendering from other locations however, such as the Broswer window, Load dialogues etc.  Please note that what we are rendering is the Scene so settings saved with the scene will be what is used (by default) in Task Rendering.  Some options can be changed in the fields provided in the Task Rendering dialogue but it's generally best to save those options with the Scene.

Merge Columns
There are a number of whats to merge columns but perhaps the easiest non-destructive means is to select the desired columns and choose Collapse.  This will place all of the columns into a subxsheet.  Creating a new Plastic mesh will then see that as all of the columns combined.  Just make sure that only those columns you want to drive the creation of the mesh are selected when creating the subxsheet.

If you can share a project that is causing your problems that will help.
Using File > Export Scene and setting a name for the project directory... then zipping up that directory can help.

Short of that...
Try creating an ultra simple shape (say a vector square or circle) and use that to work through the ins and outs of Plastic Tool usage.  If you can get to the point where you are confident working with a simple scene then it's mostly a matter of scale in working with more complex projects.  We really need to know more about your system, workflow and scenes to offer any specific advice.

**Comment by RodneyBaker** [comment]
I doubt this will be of much use but we really want to see you successfully using Plastic rigs in Opetoonz.

The attached isn't much more than a simple shape... it's a cartoon car.
A more or less random 'rig' is placed in it.

![Image](https://github.com/user-attachments/assets/01557b65-7518-4913-aa22-17cab173a4de)

Do you experience any issues with a project such as this one?

[MeshCar.zip](https://github.com/user-attachments/files/19095678/MeshCar.zip)

**Comment by andeon** [comment]
@RodneyBaker Feel free to close this issue, as I believe the PR attached here may fix it.

Anyway, it’s recommended to download the [nightly build](https://github.com/opentoonz/opentoonz/releases/tag/nightly) as it includes many important bug fixes. If the user still experiences problems after installing the new version, they can submit another issue report.
